// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'core/services/firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVG7JC-zjHdhyc6NmqKORqbo0Ksp8hhJc',
    appId: '1:1047711605350:web:6adc75a0288938c96443a7',
    messagingSenderId: '1047711605350',
    projectId: 'nile-explorer-final-app',
    authDomain: 'nile-explorer-final-app.firebaseapp.com',
    storageBucket: 'nile-explorer-final-app.firebasestorage.app',
    measurementId: 'G-WRKHFY12LJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA87SKv69HQ9NsMrJDcPaoxO5L7riSRKKg',
    appId: '1:1047711605350:android:6213ad7bd30ff5166443a7',
    messagingSenderId: '1047711605350',
    projectId: 'nile-explorer-final-app',
    storageBucket: 'nile-explorer-final-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgo_Ya0_R3IqWNubHfmRbe8F-wSdGNrnk',
    appId: '1:1047711605350:ios:6632934cac4148c46443a7',
    messagingSenderId: '1047711605350',
    projectId: 'nile-explorer-final-app',
    storageBucket: 'nile-explorer-final-app.firebasestorage.app',
    iosBundleId: 'com.example.finalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVG7JC-zjHdhyc6NmqKORqbo0Ksp8hhJc',
    appId: '1:1047711605350:web:481a59defe07abf56443a7',
    messagingSenderId: '1047711605350',
    projectId: 'nile-explorer-final-app',
    authDomain: 'nile-explorer-final-app.firebaseapp.com',
    storageBucket: 'nile-explorer-final-app.firebasestorage.app',
    measurementId: 'G-FZ15WNM438',
  );
}
